version: '3.7'

services:
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile.prod
    depends_on:
      - db
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      - static_volume:/home/app/api/project/static
      - ./api/:/usr/src/app/
    expose:
      - 5000
    env_file:
      - ./api/.env.prod
    container_name: api

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./api/.env.prod.db
  
  nginx:
    build: ./api/nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/home/app/api/project/static
    depends_on:
      - api
  
  client:
    build: ./client/
    volumes:
      - ./client/project:/usr/src
    depends_on:
      - db
      - api
    ports:
      - 3000:3000
    stdin_open: true
    container_name: client
    command: ["npm", "start"]

volumes:
  postgres_data:
  static_volume: