version: '3.7'

services:
  api:
    build: ./api/
    depends_on:
      - db
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./api/:/usr/src/app/
      - static_volume:/home/app/api/project/static
    expose:
      - 5000
    env_file:
      - ./api/.env.dev
    container_name: api
  
  client:
    build: ./client/
    volumes:
      - ./client/project:/usr/src
    depends_on:
      - db
      - api
    ports:
      - 3000:3000
    stdin_open: true
    container_name: client

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=schedule_generator

volumes:
  postgres_data: